name: Generate PDF
on: [push] # Wird bei jedem Push/Commit ausgeführt
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: dev
          output_dir: output
      - uses: actions/upload-artifact@v4 # Speichert das PDF als Download
        with:
          name: PDF-Dokument
          path: output/readme.pdf
